In [1]:
# https://www.kaggle.com/shivamkushwaha/bbc-full-text-document-classification
!wget -nc https://lazyprogrammer.me/course_files/nlp/bbc_text_cls.csv

--2026-03-18 15:05:18--  https://lazyprogrammer.me/course_files/nlp/bbc_text_cls.csv
Resolving lazyprogrammer.me (lazyprogrammer.me)... 172.67.213.166, 104.21.23.210, 2606:4700:3030::ac43:d5a6, ...
Connecting to lazyprogrammer.me (lazyprogrammer.me)|172.67.213.166|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 5085081 (4.8M) [text/csv]
Saving to: ‘bbc_text_cls.csv’

bbc_text_cls.csv    100%[===================>]   4.85M  --.-KB/s    in 0.06s

2026-03-18 15:05:18 (79.4 MB/s) - ‘bbc_text_cls.csv’ saved [5085081/5085081]

In [2]:
import pandas as pd
import numpy as np
import textwrap
from pprint import pprint
from transformers import pipeline

In [4]:
df = pd.read_csv('bbc_text_cls.csv')

In [5]:
df.head()

                                                text    labels
0  Ad sales boost Time Warner profit\n\nQuarterly...  business
1  Dollar gains on Greenspan speech\n\nThe dollar...  business
2  Yukos unit buyer faces loan claim\n\nThe owner...  business
3  High fuel prices hit BA's profits\n\nBritish A...  business
4  Pernod takeover talk lifts Domecq\n\nShares in...  business

In [6]:
labels = set(df['labels'])
print(labels)

{'business', 'politics', 'entertainment', 'sport', 'tech'}

In [7]:
# picking a label
label = "business"

In [8]:
texts = df[df['labels'] == label]['text']
texts.head()

0    Ad sales boost Time Warner profit\n\nQuarterly...
1    Dollar gains on Greenspan speech\n\nThe dollar...
2    Yukos unit buyer faces loan claim\n\nThe owner...
3    High fuel prices hit BA's profits\n\nBritish A...
4    Pernod takeover talk lifts Domecq\n\nShares in...
Name: text, dtype: object

In [9]:
np.random.seed(1234)

In [10]:
i = np.random.choice(texts.shape[0])
doc = texts.iloc[i]

In [11]:
print(textwrap.fill(doc, replace_whitespace = False, fix_sentence_endings=True))

Bombardier chief to leave company

Shares in train and plane-making
giant Bombardier have fallen to a 10-year low following the departure
of its chief executive and two members of the board.

Paul Tellier,
who was also Bombardier's president, left the company amid an ongoing
restructuring.  Laurent Beaudoin, part of the family that controls the
Montreal-based firm, will take on the role of CEO under a newly
created management structure.  Analysts said the resignations seem to
have stemmed from a boardroom dispute.  Under Mr Tellier's tenure at
the company, which began in January 2003, plans to cut the worldwide
workforce of 75,000 by almost a third by 2006 were announced.  The
firm's snowmobile division and defence services unit were also sold
and Bombardier started the development of a new aircraft seating 110
to 135 passengers.

Mr Tellier had indicated he wanted to stay at the
world's top train maker and third largest manufacturer of civil
aircraft until the restructuring was complete.  But Bombardier has
been faced with a declining share price and profits.  Earlier this
month the firm said it earned $10m (£19.2m) in the third quarter, down
from a profit of $133m a year ago.  "I understand the board's concern
that I would not be there for the long-term and the need to develop
and execute strategies, and the need to reshape the management
structure at this time," Mr Tellier said in a statement on Monday.
Bombardier said restructuring plans drawn up by Mr Tellier's would
continue to be implemented.  Shares in Bombardier lost 65 Canadian
cents or 25% on the news to 1.90 Canadian dollars before rallying to
2.20 Canadian dollars.

In [12]:
mlm = pipeline('fill-mask')

No model was supplied, defaulted to distilbert/distilroberta-base and revision fb53ab8.
Using a pipeline without specifying a model name and revision in production is not recommended.

config.json:   0%|          | 0.00/480 [00:00<?, ?B/s]

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.
WARNING:huggingface_hub.utils._http:Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

model.safetensors:   0%|          | 0.00/331M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/106 [00:00<?, ?it/s]

RobertaForMaskedLM LOAD REPORT from: distilbert/distilroberta-base
Key                         | Status     |  |
----------------------------+------------+--+-
roberta.pooler.dense.bias   | UNEXPECTED |  |
roberta.pooler.dense.weight | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

tokenizer_config.json:   0%|          | 0.00/25.0 [00:00<?, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [13]:
mlm('Bombardier chief to leave <mask>')

[{'score': 0.0695074275135994,
  'token': 633,
  'token_str': ' job',
  'sequence': 'Bombardier chief to leave job'},
 {'score': 0.06693043559789658,
  'token': 1470,
  'token_str': ' France',
  'sequence': 'Bombardier chief to leave France'},
 {'score': 0.052734989672899246,
  'token': 558,
  'token_str': ' office',
  'sequence': 'Bombardier chief to leave office'},
 {'score': 0.025822913274168968,
  'token': 2201,
  'token_str': ' Paris',
  'sequence': 'Bombardier chief to leave Paris'},
 {'score': 0.02136835642158985,
  'token': 896,
  'token_str': ' Canada',
  'sequence': 'Bombardier chief to leave Canada'}]

In [17]:
text = 'Shares in <mask> and plane-making' + \
    'giant Bombardier have fallen to a 10-year low following the departure' + \
    'of its chief executive and two members of the board.'

pprint(mlm(text))

[{'score': 0.6206179261207581,
  'sequence': 'Shares in Airbus and plane-makinggiant Bombardier have fallen '
              'to a 10-year low following the departureof its chief executive '
              'and two members of the board.',
  'token': 11016,
  'token_str': ' Airbus'},
 {'score': 0.322257399559021,
  'sequence': 'Shares in Boeing and plane-makinggiant Bombardier have fallen '
              'to a 10-year low following the departureof its chief executive '
              'and two members of the board.',
  'token': 6722,
  'token_str': ' Boeing'},
 {'score': 0.0072267260402441025,
  'sequence': 'Shares in airlines and plane-makinggiant Bombardier have fallen '
              'to a 10-year low following the departureof its chief executive '
              'and two members of the board.',
  'token': 8537,
  'token_str': ' airlines'},
 {'score': 0.0054693338461220264,
  'sequence': 'Shares in Renault and plane-makinggiant Bombardier have fallen '
              'to a 10-year low following the departureof its chief executive '
              'and two members of the board.',
  'token': 14833,
  'token_str': ' Renault'},
 {'score': 0.005017402116209269,
  'sequence': 'Shares in France and plane-makinggiant Bombardier have fallen '
              'to a 10-year low following the departureof its chief executive '
              'and two members of the board.',
  'token': 1470,
  'token_str': ' France'}]

In [18]:
text = 'Shares in train and plane-making' + \
    'giant Bombardier have fallen to a 10-year low following the <mask>' + \
    'of its chief executive and two members of the board.'

pprint(mlm(text))

[{'score': 0.570010781288147,
  'sequence': 'Shares in train and plane-makinggiant Bombardier have fallen to '
              'a 10-year low following the resignationof its chief executive '
              'and two members of the board.',
  'token': 6985,
  'token_str': ' resignation'},
 {'score': 0.15406231582164764,
  'sequence': 'Shares in train and plane-makinggiant Bombardier have fallen to '
              'a 10-year low following the departureof its chief executive and '
              'two members of the board.',
  'token': 5824,
  'token_str': ' departure'},
 {'score': 0.11344404518604279,
  'sequence': 'Shares in train and plane-makinggiant Bombardier have fallen to '
              'a 10-year low following the dismissalof its chief executive and '
              'two members of the board.',
  'token': 14289,
  'token_str': ' dismissal'},
 {'score': 0.033799778670072556,
  'sequence': 'Shares in train and plane-makinggiant Bombardier have fallen to '
              'a 10-year low following the departuresof its chief executive '
              'and two members of the board.',
  'token': 25624,
  'token_str': ' departures'},
 {'score': 0.026769310235977173,
  'sequence': 'Shares in train and plane-makinggiant Bombardier have fallen to '
              'a 10-year low following the retirementof its chief executive '
              'and two members of the board.',
  'token': 3832,
  'token_str': ' retirement'}]

In [19]:
text = 'Shares in train and plane-making' + \
    'giant Bombardier have fallen to a 10-year low following the departure' + \
    'of its chief <mask> and two members of the board.'

pprint(mlm(text))

[{'score': 0.982181966304779,
  'sequence': 'Shares in train and plane-makinggiant Bombardier have fallen to '
              'a 10-year low following the departureof its chief executive and '
              'two members of the board.',
  'token': 1031,
  'token_str': ' executive'},
 {'score': 0.012368752621114254,
  'sequence': 'Shares in train and plane-makinggiant Bombardier have fallen to '
              'a 10-year low following the departureof its chief executives '
              'and two members of the board.',
  'token': 4585,
  'token_str': ' executives'},
 {'score': 0.0014676236314699054,
  'sequence': 'Shares in train and plane-makinggiant Bombardier have fallen to '
              'a 10-year low following the departureof its chief officer and '
              'two members of the board.',
  'token': 1036,
  'token_str': ' officer'},
 {'score': 0.0010925920214504004,
  'sequence': 'Shares in train and plane-makinggiant Bombardier have fallen to '
              'a 10-year low following the departureof its chief economist and '
              'two members of the board.',
  'token': 7473,
  'token_str': ' economist'},
 {'score': 0.0008864498813636601,
  'sequence': 'Shares in train and plane-makinggiant Bombardier have fallen to '
              'a 10-year low following the departureof its chief engineer and '
              'two members of the board.',
  'token': 8083,
  'token_str': ' engineer'}]

In [20]:
text = 'Shares in train and plane-making' + \
    'giant Bombardier have fallen to a 10-year low following the departure' + \
    'of its chief executive and two <mask> of the board.'

pprint(mlm(text))

[{'score': 0.9087892174720764,
  'sequence': 'Shares in train and plane-makinggiant Bombardier have fallen to '
              'a 10-year low following the departureof its chief executive and '
              'two members of the board.',
  'token': 453,
  'token_str': ' members'},
 {'score': 0.05851733312010765,
  'sequence': 'Shares in train and plane-makinggiant Bombardier have fallen to '
              'a 10-year low following the departureof its chief executive and '
              'two thirds of the board.',
  'token': 29193,
  'token_str': ' thirds'},
 {'score': 0.014778463169932365,
  'sequence': 'Shares in train and plane-makinggiant Bombardier have fallen to '
              'a 10-year low following the departureof its chief executive and '
              'two directors of the board.',
  'token': 5392,
  'token_str': ' directors'},
 {'score': 0.0031101193744689226,
  'sequence': 'Shares in train and plane-makinggiant Bombardier have fallen to '
              'a 10-year low following the departureof its chief executive and '
              'two chairs of the board.',
  'token': 10826,
  'token_str': ' chairs'},
 {'score': 0.0026378431357443333,
  'sequence': 'Shares in train and plane-makinggiant Bombardier have fallen to '
              'a 10-year low following the departureof its chief executive and '
              'two chiefs of the board.',
  'token': 15201,
  'token_str': ' chiefs'}]